/**
 * slug-audit — companion redirect generator for the Migration Report Schema v1.0.
 *
 * Compares pre-migration slugs (source_url) against post-migration paths
 * (destination_path) from any conforming migration-report.json and generates
 * redirect rules in four formats: Nginx, Caddy, Cloudflare Pages `_redirects`,
 * and Netlify `_redirects`.
 *
 * A natural complement to any migration tool (Portage and others) and to
 * LinkCanary: Portage emits the report, slug-audit turns it into redirect
 * rules, LinkCanary verifies the result resolves.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { MigrationReportSchema } from './report.js';
import type { MigrationReport } from './report.js';

export type RedirectFormat = 'nginx' | 'caddy' | 'netlify' | 'cloudflare';

export interface RedirectRule {
  /** Old path on the source site (starts with '/'). */
  source: string;
  /** New path on the destination site; null for 410 Gone rules. */
  target: string | null;
  status: 301 | 410;
}

export interface AuditOptions {
  /** Emit 410 Gone rules for excluded/quarantined records (default false). */
  gone?: boolean;
}

/**
 * Derives redirect rules from a migration report.
 *
 * - `migrated` / `redirected` records with a destination → 301 rule
 *   (skipped when source and destination paths are identical — no redirect
 *   needed, they are the same URL).
 * - `excluded` / `quarantined` records → 410 Gone rules, only with `gone`.
 * - `failed` records are never emitted: they need review, not a redirect.
 */
export function auditRedirects(report: MigrationReport, opts: AuditOptions = {}): RedirectRule[] {
  const rules = new Map<string, RedirectRule>();
  const add = (rule: RedirectRule) => {
    if (!rule.source.startsWith('/')) return;
    if (!rules.has(rule.source)) rules.set(rule.source, rule);
  };

  for (const record of report.records) {
    const source = pathFromUrl(record.source_url);
    if (!source) continue;

    if (record.status === 'migrated' || record.status === 'redirected') {
      const target = record.destination_path ?? pathFromUrlOrPath(record.redirect_target ?? '');
      if (!target) continue;
      if (source === target) continue; // same URL before and after — nothing to redirect
      add({ source, target, status: 301 });
    } else if (opts.gone && (record.status === 'excluded' || record.status === 'quarantined')) {
      add({ source, target: null, status: 410 });
    }
  }

  return [...rules.values()].sort((a, b) => a.source.localeCompare(b.source));
}

function pathFromUrl(url: string): string | null {
  try {
    return new URL(url).pathname || '/';
  } catch {
    return null;
  }
}

function pathFromUrlOrPath(value: string): string | null {
  if (value.startsWith('/')) return value;
  return pathFromUrl(value);
}

/** Percent-encodes spaces and non-ASCII bytes; leaves existing escapes alone. */
function encodePath(p: string): string {
  return p.replace(/[^\x21-\x7E]/g, (ch) => encodeURIComponent(ch));
}

// ── Formatters ───────────────────────────────────────────────────────────

const HEADER = '# Generated by portage slug-audit — migration redirect rules';

/** Nginx: exact-match location blocks inside a server { } context. */
export function toNginx(rules: RedirectRule[]): string {
  const lines = [HEADER, '# Place inside a server { } block.', ''];
  for (const r of rules) {
    const src = encodePath(r.source);
    if (r.status === 410) {
      lines.push(`location = ${src} { return 410; }`);
    } else {
      lines.push(`location = ${src} { return 301 ${encodePath(r.target!)}; }`);
    }
  }
  return lines.join('\n') + '\n';
}

/** Caddy: redir / respond directives; import with `import Caddyfile.redirects`. */
export function toCaddy(rules: RedirectRule[]): string {
  const lines = [HEADER, '# Import with: import Caddyfile.redirects', ''];
  for (const r of rules) {
    if (r.status === 410) {
      lines.push(`respond ${encodePath(r.source)} 410`);
    } else {
      lines.push(`redir ${encodePath(r.source)} ${encodePath(r.target!)} permanent`);
    }
  }
  return lines.join('\n') + '\n';
}

/**
 * Netlify / Cloudflare Pages `_redirects` file (the two share the format —
 * the same content works for both; only the file location differs: Netlify
 * wants it at the publish-directory root, Cloudflare at the Pages output root).
 */
export function toRedirectsFile(rules: RedirectRule[]): string {
  const lines = [HEADER, '# Compatible with Netlify and Cloudflare Pages _redirects.', ''];
  for (const r of rules) {
    if (r.status === 410) {
      lines.push(`${encodePath(r.source)}  410`);
    } else {
      lines.push(`${encodePath(r.source)}  ${encodePath(r.target!)}  301`);
    }
  }
  return lines.join('\n') + '\n';
}

export function formatRules(rules: RedirectRule[], format: RedirectFormat): string {
  switch (format) {
    case 'nginx': return toNginx(rules);
    case 'caddy': return toCaddy(rules);
    case 'netlify':
    case 'cloudflare': return toRedirectsFile(rules);
  }
}

// ── File writers ─────────────────────────────────────────────────────────

const OUTPUT_FILENAMES: Record<RedirectFormat, string> = {
  nginx: 'nginx-redirects.conf',
  caddy: 'Caddyfile.redirects',
  netlify: '_redirects',
  cloudflare: '_redirects', // identical content; only placement differs
};

export interface AuditFile {
  format: RedirectFormat;
  path: string;
}

export function writeAuditFiles(rules: RedirectRule[], outDir: string, formats: RedirectFormat[]): AuditFile[] {
  const written: AuditFile[] = [];
  const wantNetlify = formats.includes('netlify');

  for (const format of formats) {
    // Netlify and Cloudflare share one file — write it once.
    if (format === 'cloudflare' && wantNetlify) continue;
    const path = resolve(outDir, OUTPUT_FILENAMES[format]);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, formatRules(rules, format), 'utf-8');
    written.push({ format, path });
  }
  return written;
}

// ── Report loading ───────────────────────────────────────────────────────

/** Reads and validates a migration-report.json (v1.0 standard). */
export function loadReport(reportPath: string): MigrationReport {
  const raw = readFileSync(reportPath, 'utf-8');
  const parsed: unknown = JSON.parse(raw);
  return MigrationReportSchema.parse(parsed);
}
